name = "eXaMINe"
license = "MIT"
licenselink = "https://github.com/mdavistffhrtporg/examine/blob/master/LICENSE.md"
description = "Fork of eXtremely Minimal Hugo theme: about 150 lines of code in total, including HTML and CSS"
homepage = "https://mdavis.me/"
demosite = "https://mdavis.me/"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Matthew A. Davis"
  homepage = "https://mdavis.me/"
